[package]
name = "i2pr-irc-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[dependencies]
i2pr-irc-core = { path = "../core" }
i2pr-irc-wire = { path = "../wire" }
tokio.workspace = true
thiserror.workspace = true
base64.workspace = true
zeroize.workspace = true
[dev-dependencies]
i2pr-irc-testkit = { path = "../testkit" }
async-trait.workspace = true
tokio = { workspace = true, features = ["test-util"] }
[lints]
workspace = true
